name: 'Custom Properties Update Action'
description: 'Updates the custom properties in a repository'
author: 'Andrew Brandt <andrew.brandt@hashgraph.com>'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  token:
    description: 'Personal Access Token'
    required: true


permissions:
  contents: read
  actions: read

runs:
  using: "composite"

  steps:
    - name: Echo hello world
      shell: bash
      run: echo "Hello World"

    - name: Print the current github information
      shell: bash
      run: |
        echo "Current variables:"
        echo "Full repo org/repo name: ${{ github.repository }}"
        echo "Repo owner: ${{ github.repository_owner }}"
        echo "Repo name: ${{ github.event.repository.name }}"

    - name: Install tools
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y yq

    - name: Parse repo-properties.yaml and export metadata
      shell: bash
      run: |
        REPO_NAME=${{ github.event.repository.name }}
        YAML_FILE="repo-properties.yaml"
        
        echo "pwd here"
        pwd
        
        echo "ls here"
        ls
        
        echo "repo name:"
        echo ${REPO_NAME}
        
        echo "yaml file:"
        echo ${YAML_FILE}
        
        # Get all fields for the matching repo (as a JSON object)
        JSON_values=$(yq eval -o=json repo-properties.yaml)
