name: 'Custom Properties Update Action'
description: 'Updates custom properties in repos'
author: 'Andrew Brandt <andrew.brandt@hashgraph.com>'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  yaml_file:
    description: 'Path to the YAML file'
    required: true
    default: 'repos.yaml'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        sudo snap install yq
      shell: bash

    - name: Validate YAML file
      run: |
        if [[ ! -f "${{ inputs.yaml_file }}" ]]; then
          echo "Error: YAML file not found!"
          exit 1
        fi
      shell: bash

    - name: Read YAML and update repository property
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        YAML_FILE="${{ inputs.yaml_file }}"

        ORG=$(yq e '.org' "$YAML_FILE")
        REPOS=$(yq e '.repositories[].name' "$YAML_FILE")

        if [[ -z "$ORG" ]]; then
          echo "Error: Organization name is empty!"
          exit 1
        fi

        if [[ -z "$REPOS" ]]; then
          echo "Error: No repositories found in YAML!"
          exit 1
        fi

        for REPO in $REPOS; do
          LAST_MODIFIED=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Updating $ORG/$REPO with last-date-modified: $LAST_MODIFIED"

          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$ORG/$REPO \
            -d "{\"custom_properties\": {\"last-date-modified\": \"$LAST_MODIFIED\"}}")

          if [[ "$RESPONSE" -ne 200 ]]; then
            echo "Error: Failed to update $ORG/$REPO. Response Code: $RESPONSE"
            cat response.json
            exit 1
          fi
        done
      shell: bash

