name: 'Custom Properties Update Action'
description: 'Updates the custom properties in a repository'
author: 'Andrew Brandt <andrew.brandt@hashgraph.com>'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  governance-repo-url:
    description: 'Git URL of the governance repo'
    required: true
  token:
    description: 'Personal Access Token'
    required: true


permissions:
  contents: read
  actions: read

runs:
  using: "composite"

  steps:
    - name: Echo hello world
      shell: bash
      run: echo "Hello World"

    - name: Clone governance repo
      shell: bash
      run: |
        git clone --depth 1 "${{ inputs.governance-repo-url }}" governance-repo
        echo "Cloned governance repo"
        echo "Running pwd now"
        pwd
        echo "Running ls now"
        ls -la

    - name: Print the current github information
      shell: bash
      run: |
        echo "Current variables:"
        echo "Full repo org/repo name: ${{ github.repository }}"
        echo "Repo name: ${{ github.event.repository.name }}"
        echo "Repo owner: ${{ github.repository_owner }}"
    
        
