name: 'Custom Properties Update Action'
description: 'Updates the custom properties in a repository'
author: 'Andrew Brandt <andrew.brandt@hashgraph.com>'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  governance-repo-url:
    description: 'Git URL of the governance repo'
    required: true

permissions:
  id-token: read
  contents: read
  actions: read

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      id: checkout_code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: "0"
        ref: ${{ steps.validate.outputs.build-tag }}
        token: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Clone governance repo
      run: |
        git clone --depth 1 "${{ inputs.governance-repo-url }}" governance-repo
        echo "Cloned governance repo"
        echo "Running ls now"
        ls -la

#    - name: Install tools
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y jq yq
#
#    - name: Parse repo-properties.yaml and export metadata
#      shell: bash
#      run: |
#        REPO_NAME=$(basename "${GITHUB_REPOSITORY}")
#        YAML_FILE="governance-repo/repo-properties.yaml"
#
#        # Get all fields for the matching repo (as a JSON object)
#        JSON=$(yq -o=json '.repositories[] | select(.name == strenv(REPO_NAME))' repo-properties.yaml)
#        echo "Current JSON file is:"
#        echo ${JSON}
#
#        # Remove the "name" field (not a property)
#        JSON_WITHOUT_NAME=$(echo "$JSON" | jq 'del(.name)')
#        echo "Current JSON_WITHOUT_NAME file is:"
#        echo ${JSON_WITHOUT_NAME}
#
#        echo "Setting these custom properties:"
#        echo "${JSON_WITHOUT_NAME}"
#
#        curl -X PATCH "https://api.github.com/repos/$OWNER/$REPO_NAME/properties" \
#          -H "Authorization: Bearer $GH_TOKEN" \
#          -H "Accept: application/vnd.github+json" \
#          -H "X-GitHub-Api-Version: 2022-11-28" \
#          -H "Content-Type: application/json" \
#          -d "$JSON_WITHOUT_NAME"
