name: 'Custom Properties Update Action'
description: 'Updates the custom properties in a repository'
author: 'Andrew Brandt <andrew.brandt@hashgraph.com>'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  governance-repo-url:
    description: 'Git URL of the governance repo'
    required: true
  token:
    description: 'Personal Access Token'
    required: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

runs:
  using: "composite"
  steps:
    - name: Echo hello world
      run: echo "Hello World"
