name: 'Custom Properties Update Action'
description: 'Updates the custom properties in a repository'
author: 'Andrew Brandt <andrew.brandt@hashgraph.com>'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  governance-repo-url:
    description: 'Git URL of the governance repo'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Clone governance repo
      run: |
        git clone --depth 1 "${{ inputs.governance-repo-url }}" governance-repo

    - name: Parse repo-properties.yaml and export metadata
      shell: bash
      run: |
        REPO_NAME=$(basename "${GITHUB_REPOSITORY}")
        YAML_FILE="governance-repo/repo-properties.yaml"

        if ! command -v yq >/dev/null 2>&1; then
          echo "Installing yq..."
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
        fi

        LAST_UPDATE_BY=$(yq ".repositories[] | select(.name == \"${REPO_NAME}\") | .\"last-update-by\"" "$YAML_FILE")
        LAST_DATE_MODIFIED=$(yq ".repositories[] | select(.name == \"${REPO_NAME}\") | .\"last-date-modified\"" "$YAML_FILE")

        echo "last-update-by=${LAST_UPDATE_BY}" >> $GITHUB_ENV
        echo "last-date-modified=${LAST_DATE_MODIFIED}" >> $GITHUB_ENV

        echo "Custom properties set: "
        echo "  last-update-by=${LAST_UPDATE_BY}"
        echo "  last-date-modified=${LAST_DATE_MODIFIED}"
